[package]
name = "MessAuto"
version = "0.2.0"
edition = "2021"
description = "Automatic extraction of SMS verification code for Mac platform."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sys-locale = "0.3.0"
tray-icon = "0.4.4"
tao = { git = "https://github.com/tauri-apps/tao", branch = "muda" }
rust-i18n = "1.1.4"
once_cell = "1.17.1"
serde_json = "1.0.95"
serde = "1.0.159"
home = "0.5.4"
auto-launch = "0.4.0"
native-dialog = "0.6.3"
macos-accessibility-client = "0.0.1"
regex = "1.7.3"
enigo = "0.1.2"
clipboard = "0.5.0"

[package.metadata.i18n]
available-locales = ["en", "zh-CN"]
default-locale = "en"
load-path = "locales"

[package.metadata.bundle]
name = "MessAuto"
identifier = "com.doe.messauto"
icon = ["images/icon.icns"]
copyright = "Copyright (c) LeeeSe 2022. All rights reserved."
short_description = "Automatic extraction of SMS verification code for Mac platform."
