name: Rust

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          profile: minimal
          override: true

    - name: Install dependencies
      run: cargo install cargo-bundle

    - name: Add aarch64 target
      run: rustup target add aarch64-apple-darwin
      
    - name: Bundle for x86_64
      run: cargo bundle --release

    - name: Bundle for aarch64
      run: cargo bundle --target aarch64-apple-darwin --release

    - name: Create Release Draft
      uses: release-drafter/release-drafter@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#    - name: tests
#      run: cargo test

